image: node:lts-alpine

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - apk add --no-cache --virtual .gyp python3 make g++
  - npm install
  - apk del .gyp

# Vos étapes de tests...

build:
  stage: build
  script:
    - npm run build-npm
  artifacts:
    paths:
      - dist

publish_npm:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  dependencies:
    - build
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm publish --access public
  only:
    - master