  name: Deploy to Github Pages
  on:
    push:
      branches:
        - master
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '18'
          - name: Config npm
            run:  npm config set legacy-peer-deps=true --location=project
          - name: Install packages
            run: npm i
          - name: Set Creds
            run: git config user.name "lipme" && git config user.email "lipme-bioinfo@inrae.fr"
          - name: Deploy
            run: npm run deploy